### ISSUE TITLE
Some feedback from setting up locally

### ISSUE THREAD

**Issue by davisshaver** [newslynx/newslynx-core#10]
- The Postgres.app URL takes this pattern: `postgresql://USER:USERPW@localhost:5432/newslynx`
- `make defaults` should be run before `newslynx gen_random_data`
- Redis should be installed prior to generating random data. Easiest is to do `brew install redis` and then we can leave it running in a terminal window for `redis-server /usr/local/etc/redis.conf`.

**Comment by abelsonlive** [comment]
Thanks! Will put this in a "Local Install" Guide.

**Comment by abelsonlive** [comment]
Hey thanks for this. We've actually completed an automation process which you can check out here: 

https://github.com/newslynx/automation
