### ISSUE TITLE
Thumbnail Cache Prefix Issue 

### ISSUE THREAD

**Issue by miguelcarvajal** [newslynx/newslynx-core#9]
Hi! I am testing the app locally for my news project. Do you guys know what could be the solution to this issue?

When I run ``newslynx init``, the thread works fine till I got this error:

``key_prefix = settings.THUMBNAIL_CACHE_PREFIX
AttributeError: 'module' object has no attribute 'THUMBNAIL_CACHE_PREFIX'``

In my ``config.yaml``, I have this configuration:

`url cache url_cache_prefix: newslynx-url-cache url_cache_ttl: 259200 # 3 days url_cache_pool_size: 5 # extraction cache extract_cache_prefix: newslynx-extract-cache extract_cache_ttl: 259200 # 3 days``

Thank you for your help.

**Comment by abelsonlive** [comment]
hey miguel! we're not quite ready for the big-time yet.  I'll make sure to ping you when we've fully documented the build process. 

Not sure why you would get that problem. There are numerous things you can configure with `newslynx`, but most of this fallback on the defaults set here: https://github.com/newslynx/newslynx/blob/master/newslynx/defaults.py. Maybe try pulling the latest version and reinstalling?

**Comment by miguelcarvajal** [comment]
Thanks. I will pull the latest version and reinstall again. Cheers!
